app:
  name: customers
server:
  port: 8002
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
warehouse:
  rabbitmq:
    queue: customers.queue
    exchange: shop.fanout
---
spring:
    profiles: docker
    rabbitmq:
      host: rabbitmq
server:
    port: 8000
