app:
  name: authserver
server:
  port: 8000
spring:
  datasource:
    url: "jdbc:h2:./database/samspledb;AUTO_SERVER=TRUE"
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
---
spring:
    profiles: docker
server:
    port: 8000