app:
  name: billing
server:
  port: 8003
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
billing:
  rabbitmq:
    queue: billing.queue
    exchange: shop.fanout
---
spring:
    profiles: docker
    rabbitmq:
      host: rabbitmq
server:
    port: 8000
